### ISSUE TITLE
PPLNS calc algorithm query

### ISSUE THREAD

**Issue by oschonrock** [Snipa22/nodejs-pool#111]
Is seems the PPLNS payment calc is in this function:
function calculatePPLNSPayments(blockHeader) 
https://github.com/Snipa22/nodejs-pool/blob/master/lib/blockManager.js#L206

Can you confirm whether this implements the “unit-PPLNS” algorithm as described here:
https://arxiv.org/pdf/1112.4980.pdf

> To be completely hopping-proof, the following method, called “unit-PPLNS”,
> should be used: ... (on page 11)

briefly looking at the code, it seemed to me that it may be using something simpler, which may not be "hopping proof"? (could be that I didn't understand the algo from the code )

Thanks

**Comment by Snipa22** [comment]
We implement a simpler system, functionally where it's the last N shares, where N is found block diff * the PPLNS modifier.  The main issue we're patching is the RBPPS system, which allowed for utter hopping and abuse.

Technically, this still permits light abuse via hopping, but you'd have to submit a massive number of shares within the N period, which gets shorter as the number of hashes/second goes up.  Technically, you could throw a massive amount of hash into the pool, which would remain as the value of N went down, however, your share would decrease expectedly over time, unlike RBPPS, where you would likely maintain a large portion of the block.

PPLNS basic is very easy to abuse with fixed difficulty changes, as the paper describes, as you could move large number of h/s to the pool right before a diff drop, then your shares would be worth more than their expected value over the time of N.  However, as CN/XMR are the primary targets for this code at the moment, it's not as much of a concern due to the continually shifting difficulty, and if you controlled enough nethash to control the difficulty, there's other concerns.

**Comment by oschonrock** [comment]
OK. Makes sense, sounds like it's "not perfect", but not a priority due to current state of maturity (?) of the XMR blockchain. 

Or is there something fundamental to the way XMR/CN works that makes the difficulty adjust more continuously and hence be less subject to "difficulty-based pool hopping".

**Comment by Snipa22** [comment]
This is integral to the XMR blockchain.  Every block receives a new difficulty based on the duration of time to mine the last 720 blocks:  https://monero.stackexchange.com/a/1010

**Comment by oschonrock** [comment]
Right, yes. I knew that, but had forgotten. Thanks. I'll can close this I guess. Worth having on record that XMR does not need  “unit-PPLNS” as per that paper and simpler algos are sufficient.
