### ISSUE TITLE
Aeon install 

### ISSUE THREAD

**Issue by newhelp** [Snipa22/nodejs-pool#185]
Please share how to install Aeon Pool, please.

**Comment by ArqTras** [comment]
Using aeon deploy.bash but correct daemon path, change in sql ports of aeon daemon and wallet.
Many many changes to do.

**Comment by ArqTras** [comment]
Pool working ticket to close

**Comment by CoinLogik** [comment]
@ArqTras can you share your work?

**Comment by ArqTras** [comment]
@CoinLogik Its all public. You can get installation for Electroneum + wiki for node (aeon).
Of you need aeon need to change few lines in deploy bash or manual install aeond on screen and comment in deploy.bash what is useless. I make a little mess because I created working solution for one coin ETN that cannot be merged to Snippa22 repository. You can find all info on my github.

**Comment by TimeTravelersHackedMe** [comment]
@ArqTras do we need to create Aeon wallet addresses? Also, what other things do we have to change in the base.sql? What about ('payout', 'shapeshiftPair', 'xmr_btc', 'string', 'Pair to use in all shapeshift lookups for auto BTC payout');?

**Comment by TimeTravelersHackedMe** [comment]
Also, there's this line too: ('payout', 'bestExchange', 'xmrto', 'string', 'Current best exchange');

**Comment by ArqTras** [comment]
You need to create pool wallet and run it in special commands. Add wallets to MySQL config(pool and fee). Shapeshiftnkt tested
