### ISSUE TITLE
My AEON pool found a block, but the miner's balances are wrong

### ISSUE THREAD

**Issue by vitorgatti** [Snipa22/nodejs-pool#263]
My AEON pool found a block and got ~11 AEON, but my miners, on the whole sum (only 5 miners), checking the `balance` table in MySQL, got much less (something like 4 AEON total).

What did I do wrong? What adjustment should I make for it to work properly?

Thanks

**Comment by vitorgatti** [comment]
https://i.imgur.com/3zbBdck.png

is this expected?

**Comment by vitorgatti** [comment]
https://i.imgur.com/3zbBdck.png

Is this expected?

**Comment by ArqTras** [comment]
Wait for next block (if this is first ) 
Miners can use own threshold, so owed can be higher.
Read about PPLNS

**Comment by vitorgatti** [comment]
Yes this is the first block

Miners didn't change the threshold (checking in pool.users)

So probably in the next block this will be self-corrected?

Thanks :)

**Comment by curumimxara** [comment]
> Wait for next block (if this is first )
> Miners can use own threshold, so owed can be higher.

Hey there, I'm one of the miners on the designated pool. I represent roughly 50% of the pool's hashrate, but I've received only ~8% of the block reward. Do you think that this is because it was the first block the pool mined? So in the following blocks I'll simply get let's say, 50% of the next block + the missing 42% of the previous block (which is not on my _total due_ dashboard, it's simply nowhere)?

I have no experience managing pools, I'm just a miner, so I'm sorry if this is something considered common knowledge between pool administrators.

Thank you for your help!

**Comment by bobbieltd** [comment]
Does anyone know how to tweak this contribution so the pool always keep very low amount ( for transaction fees + total unpaid dues ) ? 
It can look like the pool steals and keep coins. It makes miners freaking out.

**Comment by ArqTras** [comment]
There is info that pool wallet should be empty for start, because wallet need some coins for transfer coins to miners wallet

**Comment by bobbieltd** [comment]
In my pool, first block the pool pays to miners less than block reward amount. But second block, the pool pays to miners more than block reward amount.
Pehaps, it’s PPLNS mechanism.

**Comment by bobbieltd** [comment]
@vitorgatti I understand better now. Because you put feesForTxn = 10 ( or whatever number), so the pool tries to keep money more to get to reserves = feesForTxn . You can lower it to 1 AEON and increase it later. Final word : the cause is feesForTxn.

**Comment by vitorgatti** [comment]
Yes that's probably it, @bobbieltd !
I changed my pool's feesForTxn to "1" and found 3 new blocks, but the pool is still keeping ~9 AEON to itself. No problem, as just me and 2 friends were mining at the time of the first block, so we'll just assume those 9 AEON are ours :)

Thanks for your help!
