### ISSUE TITLE
PPLNS algorithm

### ISSUE THREAD

**Issue by nikashitsa** [Snipa22/nodejs-pool#439]
Hi,

Does `calculatePPLNSPayments` work correct?

Our user with high hashrate was sending around 99% of hashes for short period of time and we found 4 blocks.
But PPLNS algorithm decided to pay him only reward for one block (1301). Major part of reward  for last 3 blocks (4761) got our another user with constant low hashrate. Expected that last two payments should be paid to user with high hashrate.

Can anyone explain why this happened and it's correct or not? We have `shareMulti=2`.
I've attached screenshots with details. We uses fork of this [repo](https://github.com/graftpro/nodejs-pool), but almost all code is the same.

Two last payments:  
![payments](https://user-images.githubusercontent.com/1029908/41636810-74599f94-7472-11e8-941d-b14527e906b7.jpg)

Found blocks with details:  
![blocks](https://user-images.githubusercontent.com/1029908/41636811-7479d8ea-7472-11e8-8234-766b9f52ff1b.jpg)

User with high hashrate:  
![short_user](https://user-images.githubusercontent.com/1029908/41636808-7419f5e2-7472-11e8-8d77-d113e80b0ac2.png)

User with low hashrate:  
![low_user](https://user-images.githubusercontent.com/1029908/41636809-743a8dc0-7472-11e8-8893-21e4302168db.png)

Thanks

**Comment by bobbieltd** [comment]
It seems your pool paid correctly. 1% or 99% hashrate is not important because 99% is not constant. PPLNS counts back 2*block diff or 200%. The 99% hashrate stopped quite long time ago.
If you look at Total hashes, “constant low hashrate” total is 130 billions hashes and is more than double of “99% hashrate”, so the low hashrate must have around double payments (71k GRFT vs 36k GRFT).
It seems the payments are VERY CORRECT. You get paid for what you contributed not the TEMPORARY NICEHASH PERCENTAGE.

**Comment by nikashitsa** [comment]
Ok, thank you for clarification.
