### ISSUE TITLE
autometic bash install script have problem 

### ISSUE THREAD

**Issue by bapparabi** [Snipa22/nodejs-pool#47]
when i try to run you auto install script i get an error after certain point see this ..do you know what is the iisue 

#####
Setting up binutils (2.26.1-1ubuntu1~16.04.3) ...
Setting up libdrm-intel1:amd64 (2.4.70-1~ubuntu16.04.1) ...
Setting up libdrm-radeon1:amd64 (2.4.70-1~ubuntu16.04.1) ...
Setting up mtools (4.0.18-2ubuntu0.16.04) ...
Processing triggers for libc-bin (2.23-0ubuntu5) ...
Processing triggers for initramfs-tools (0.122ubuntu8.8) ...
Errors were encountered while processing:
 sudo
E: Sub-process /usr/bin/dpkg returned an error code (1)
pooladmin@xmr:~$

#########################################

**Comment by Snipa22** [comment]
This is a bug on your local system.  Most likely during your apt-get -y upgrade, because you've tweaked the sudoers file.  This shouldn't cause a massive bug on your system during the installation, as we don't block with && during the installer.  Paste the entire log, and I'm sure that's what we'll see.

**Comment by bapparabi** [comment]
here is log http://pastebin.com/Qz3EH51d
