### ISSUE TITLE
longRunner thread memory leak

### ISSUE THREAD

**Issue by M5M400** [Snipa22/nodejs-pool#53]
the longRunner thread is eating up roughly 1GB of memory per day on my box :)

![screenshot from 2017-03-10 15-23-49](https://cloud.githubusercontent.com/assets/22886679/23798610/bb341260-05a5-11e7-8cb2-1692d1324197.png)

**Comment by Snipa22** [comment]
Can you run that free command as free -m and run: mdb_stat -fear /path/to/your/pool/db/  ?  I'm checking my main production box, and it looks fine:
https://i.imgur.com/7ToTmye.png

I suspect you're seeing a ton of things in cache at the moment, as LMDB will pre-allocate huge chunks of ram, but never use it. 

I've got a debugger up and attached to my instance, which is why it's uptime is low at the moment.  The NodeJS heap is only showing about 12Mb in use, which would suggest that this isn't nodeJS, but something else on your machine munching the used ram, so a full ps fuax would be useful to help see if there's something else ram-hungry on there.

Also, keep in mind, long-runner uses 11Gb right after bootup for me, so you're certainly not seeing a 1Gb/day increase.

**Comment by Snipa22** [comment]
Actually, now that I look at it, that's exactly what's happening.  Other node instances should be reporting 5-6 Gb of ram used * numthreads, but they're not, because the main node init.js isn't using that much RAM.  However, this is just LMDB.  Unless there's a real leak here (I don't think there is), this should be closed out.

**Comment by Snipa22** [comment]
Heap has continued to shrink on the given process, so I'm leaning towards LMDB being LMDB.  Let me know if you think otherwise still, but I'll need some proof to help with that, because this doesn't seem to be related to memory usage.

**Comment by M5M400** [comment]
Well if your long-runner uses 11GB right from restart, then behavior on your box is certainly different than mine. Mine clocks in at sub 2GB on restart and then increases ~1GB per day, as I said.

Here you go, 3 days later: Went from 12GB to 15 GB

![screenshot from 2017-03-13 09-06-09](https://cloud.githubusercontent.com/assets/22886679/23846253/eb56cd1a-07cc-11e7-93c7-1888e8ab6edf.png)

![screenshot from 2017-03-13 09-09-01](https://cloud.githubusercontent.com/assets/22886679/23846256/efac91a6-07cc-11e7-9389-43480a6d3a83.png)

**Comment by Snipa22** [comment]
According to your RSS there, you're using 15Gb in what's LongRunner, 7Gb in what's likely worker,  5Gb in Monero, then 6.5Gb in other processes.  This would put you at 32Gb ram used.  As you're not at 32Gb used, this is, quite obviously, to me, LMDB's usual memory mapping, information on this can be found at: https://lmdb.readthedocs.io/en/release/#memory-usage , this is for the python version, but as it's just a LMDB wrapper, still holds true.

I've taken another HEAP dump of my production server, and it's still right at 10Mb of memory:
-rw-r--r--   1 pooldaemon pooldaemon 12008306 Mar 10 21:01 heapdump-3591038032.183000.heapsnapshot
-rw-r--r--   1 pooldaemon pooldaemon 10357032 Mar 10 21:05 heapdump-3591254833.841618.heapsnapshot
-rw-r--r--   1 pooldaemon pooldaemon 10430974 Mar 10 21:25 heapdump-3592487699.654387.heapsnapshot
-rw-r--r--   1 pooldaemon pooldaemon 10424778 Mar 11 21:15 heapdump-3678294719.335695.heapsnapshot
-rw-r--r--   1 pooldaemon pooldaemon 10411630 Mar 13 14:15 heapdump-3825851066.328575.heapsnapshot

You'll need to do some heavier tracing on your side to determine what the RAM usage is, as I'm not able to replicate.

**Comment by M5M400** [comment]
I updated to current version and will observe if the issue persists. If not, I'll close.

**Comment by M5M400** [comment]
seems to be gone... now occupies some GB of ram right from the start, but then doesn't leak
