### ISSUE TITLE
[API] Roundhash for miner

### ISSUE THREAD

**Issue by 20dec** [Snipa22/nodejs-pool#54]
Hi,
Can you add this function for API?
When the beginning of every block found by pool. Roundhash for miner begin/reset at 0 and keep increase up to all miner hashrate till next block found by pool.
Thanks.
20Dec

**Comment by Snipa22** [comment]
Round-hash isn't a useful value for a miner unfortunately, as PPLNS doesn't calculate per-block, but rather as the percentage value of your shares, as the last N shares of your pool.  I'll be glad to add this though.

**Comment by 20dec** [comment]
I can use miner roundhash and pool roundhash to estimate % my share/pool at current round and know my reward whenever block found.

Thanks very much.
20dec

**Comment by Snipa22** [comment]
I don't think you quite understood my comment. :)  PPLNS doesn't care about roundhashes.  Only N hashes, where N is difficulty * lookback modifier, by default, that's 2, so right now, we look at approximately 13-14b shares.  Those can be in a single "round" or in 200 "rounds", which is why it's not useful. :)

**Comment by 20dec** [comment]
Yes, I don't really understand all what you said. And because I've read define of pool type here http://pastebin.com/f9EJEeQK
Then I think I can calc it as Prop pool type by using % submit of miner to pool. But please still add roundhash miner function if possible, then I can find other way to use it usefully :D For example: simple monitoring all of my miners hash submitted each round :P

Thanks very much,
20Dec
