### ISSUE TITLE
Vardiff change triggers "Low difficulty" error sometimes

### ISSUE THREAD

**Issue by SChernykh** [Snipa22/nodejs-pool#91]
I've noticed I have more invalid shares than usual, so I've checked logs and found that sometimes:

1) Pool sends new job {"jsonrpc":"2.0","method":"job","params":{...}}
2) Pool sends {"id":1,"jsonrpc":"2.0","error":{"code":-1,"message":"Low difficulty share"}} immediately after that

Even though the worker didn't send any share to check before getting the error.

This new job is vardiff change, so it's somehow related to vardiff logic.

**Comment by Snipa22** [comment]
Low difficulty share is auctually a misnomer here.  The system is changing your difficulty because it received a bad share.  https://github.com/Snipa22/nodejs-pool/blob/master/lib/pool.js#L549  I'm aware of the bug and source of this issue, and have a patch in the works.  This is related to the pool loading an incorrect block template based on the height.

**Comment by SChernykh** [comment]
Thanks for the explanation! So the messages just arrive in the wrong order which confused me.

**Comment by Snipa22** [comment]
Correct, the pool sends the job, then notifies you of the bad share.  It's more important for us to get the new job out to you so you get going mining faster. :)
